# Generated by Django 3.1.3 on 2021-05-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Choose a genre for this song', to='music.Genre'),
        ),
    ]
