# Generated by Django 3.1.3 on 2020-12-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='transactions',
        ),
    ]
