# Generated by Django 3.1.3 on 2020-12-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_auto_20201223_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='section',
            new_name='sections',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('all_transactions', models.ManyToManyField(to='budgets.Transaction')),
                ('budgets', models.ManyToManyField(to='budgets.Budget')),
            ],
        ),
    ]
