# Generated by Django 3.1.3 on 2021-01-01 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0010_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='all_transactions',
            field=models.ManyToManyField(blank=True, to='budgets.Transaction'),
        ),
    ]
