# Generated by Django 3.1.3 on 2021-01-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_budget_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('income', 'Income'), ('food', 'Food'), ('bills/utilities', 'Bills/Utilities'), ('travel', 'Travel'), ('amusement', 'Amusement'), ('misc', 'Miscellaneous')], default='misc', max_length=32, verbose_name='Transaction Type'),
        ),
    ]
