# Generated by Django 3.1.3 on 2021-01-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0013_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='sections',
        ),
        migrations.AddField(
            model_name='budget',
            name='amount_predicted',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='transactions',
            field=models.ManyToManyField(blank=True, to='budgets.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
