# Generated by Django 3.1.3 on 2021-01-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0014_auto_20210102_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Income', 'Income'), ('Food', 'Food'), ('Bills/Utilities', 'Bills/Utilities'), ('Travel', 'Travel'), ('Amusement', 'Amusement'), ('Miscellaneous', 'Miscellaneous')], max_length=32, verbose_name='Transaction Type'),
        ),
    ]
