# Generated by Django 3.1.3 on 2021-01-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0015_auto_20210103_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Income', 'Income'), ('Food', 'Food'), ('Bills/Utilities', 'Bills/Utilities'), ('Travel', 'Travel'), ('Amusement', 'Amusement'), ('Miscellaneous', 'Miscellaneous')], default='Income', max_length=32, verbose_name='Category'),
        ),
    ]
