# Generated by Django 3.1.3 on 2021-01-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0016_auto_20210103_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'Febuary'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=12, verbose_name='Month'),
            preserve_default=False,
        ),
    ]
