# Generated by Django 3.1.3 on 2021-01-05 11:27

import budgets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0018_auto_20210105_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'Febuary'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=12, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.IntegerField(validators=[budgets.models.validate_year]),
        ),
    ]
