# Generated by Django 3.1.3 on 2021-01-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0020_remove_budget_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
