# Generated by Django 3.1.3 on 2021-01-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0021_delete_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_income', models.DecimalField(decimal_places=2, max_digits=65)),
                ('pre_food', models.DecimalField(decimal_places=2, max_digits=65)),
                ('pre_bills', models.DecimalField(decimal_places=2, max_digits=65)),
                ('pre_travel', models.DecimalField(decimal_places=2, max_digits=65)),
                ('pre_amusement', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
    ]
