# Generated by Django 3.1.3 on 2021-01-05 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0023_remove_budget_amount_predicted'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budgets.template'),
            preserve_default=False,
        ),
    ]
