# Generated by Django 2.2.20 on 2021-08-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0024_auto_20210813_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['make']},
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
