# Generated by Django 3.1.3 on 2021-01-06 11:12

import budgets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0025_template_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='pre_bills',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pre_Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65)),
                ('date_expected', models.IntegerField(validators=[budgets.models.validate_date_bills])),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='pre_bills',
            field=models.ManyToManyField(to='budgets.Pre_Bills'),
        ),
    ]
